# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operation.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from ui.drag_drop_elements import table_widget_dad, tree_widget_dad


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 450)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_workers = table_widget_dad.TableWidgetDAD(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.tw_workers.setFont(font)
        self.tw_workers.setAcceptDrops(True)
        self.tw_workers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_workers.setDragEnabled(True)
        self.tw_workers.setDragDropOverwriteMode(False)
        self.tw_workers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_workers.setObjectName("tw_workers")
        self.tw_workers.setColumnCount(1)
        self.tw_workers.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tw_workers.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_workers.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_workers.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_workers.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_workers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_workers.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_workers.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_workers.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_workers.setItem(3, 0, item)
        self.tw_workers.verticalHeader().setVisible(False)
        self.tw_workers.verticalHeader().setDefaultSectionSize(20)
        self.tw_workers.verticalHeader().setMinimumSectionSize(18)
        self.gridLayout.addWidget(self.tw_workers, 0, 1, 1, 1)
        self.treeWidget = tree_widget_dad.TreeWidgetDAD(self.centralwidget)
        self.treeWidget.setAcceptDrops(True)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"")
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.pb_add = QtWidgets.QAction(MainWindow)
        self.pb_add.setObjectName("pb_add")
        self.pb_change = QtWidgets.QAction(MainWindow)
        self.pb_change.setObjectName("pb_change")
        self.pb_dell = QtWidgets.QAction(MainWindow)
        self.pb_dell.setObjectName("pb_dell")
        self.action123 = QtWidgets.QAction(MainWindow)
        self.action123.setObjectName("action123")
        self.actionEded = QtWidgets.QAction(MainWindow)
        self.actionEded.setObjectName("actionEded")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.toolBar.addAction(self.pb_add)
        self.toolBar.addAction(self.pb_change)
        self.toolBar.addAction(self.pb_dell)
        self.toolBar.addAction(self.action123)
        self.toolBar.addAction(self.actionEded)
        self.toolBar.addAction(self.action)
        self.toolBar.addAction(self.action_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Список работников"))
        item = self.tw_workers.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.tw_workers.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tw_workers.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tw_workers.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tw_workers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя"))
        __sortingEnabled = self.tw_workers.isSortingEnabled()
        self.tw_workers.setSortingEnabled(False)
        item = self.tw_workers.item(0, 0)
        item.setText(_translate("MainWindow", "Саша"))
        item = self.tw_workers.item(1, 0)
        item.setText(_translate("MainWindow", "Паша"))
        item = self.tw_workers.item(2, 0)
        item.setText(_translate("MainWindow", "Даша"))
        item = self.tw_workers.item(3, 0)
        item.setText(_translate("MainWindow", "Маша"))
        self.tw_workers.setSortingEnabled(__sortingEnabled)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Название"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "1"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "2"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "3"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.pb_add.setText(_translate("MainWindow", "Добавить"))
        self.pb_change.setText(_translate("MainWindow", "Изменить"))
        self.pb_dell.setText(_translate("MainWindow", "Удалить"))
        self.action123.setText(_translate("MainWindow", "\'    \'"))
        self.actionEded.setText(_translate("MainWindow", "Добавить"))
        self.action.setText(_translate("MainWindow", "Изменить"))
        self.action_2.setText(_translate("MainWindow", "Удалить"))

